parameters:
  vmImage: ''
  sdkVersion: ''
  buildConfiguration: ''
  projects: ''
  arguments: ''

jobs:
  - job: IntegrationTests
    displayName: Run integreation tests
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:

      - task: UseDotNet@2
        displayName: Install .NET Core SDK
        inputs:
          version: ${{ parameters.sdkVersion }}
          packageType: sdk

      - script: dotnet help
        displayName: Initialize .NET Core environment

      - task: DotNetCoreCLI@2
        displayName: Execute integration tests
        inputs:
          command: test
          projects: ${{ parameters.projects }}
          configuration: ${{ parameters.buildConfiguration }}
          arguments: >
            --verbosity normal
            ${{ parameters.arguments }}
          publishTestResults: true
