trigger:
  batch: true
  branches:
    include:
      - develop
  paths:
    exclude:
      - docs/*
      - "**/*.md"

pr:
  - develop

variables:
  - template: variables.yml

stages:
  - stage: Build
    displayName: 🚧 Build
    jobs:
      - job: Build
        displayName: Build with .NET Core SDK
        pool:
          vmImage: $(vmImage)
        steps:

          - task: UseDotNet@2
            displayName: Install .NET Core SDK
            inputs:
              version: $(sdkVersion)
              packageType: sdk

          - script: dotnet help
            displayName: Initialize .NET Core environment

          - task: DotNetCoreCLI@2
            displayName: Build project with CI version
            inputs:
              command: build
              projects: $(projectPath)
              arguments: >
                --configuration $(buildConfiguration)
                --version-suffix "$(ciVersionSuffix)"

          - bash: >
              dotnet pack
              --no-build
              --output "$(Build.ArtifactStagingDirectory)/packages/ci"
              --configuration $(buildConfiguration)
              --version-suffix "$(ciVersionSuffix)"
              $(projectPath)
            displayName: Create CI nuget package

          - publish: $(Build.ArtifactStagingDirectory)/packages
            artifact: packages

  - stage: PublishArtifacts
    dependsOn: Build
    displayName: 📤 Publish artifacts
    # publish artifacts only for pull requests that is coming from the same repo
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], False))
    jobs:
      - template: jobs/publish-artifacts.yml
        parameters:
          sdkVersion: $(sdkVersion)
          internalfeedName: $(internalfeedName)
          artifact: packages
          packages: $(Pipeline.Workspace)/packages/ci/*.*upkg
          vmImage: $(vmImage)

  - stage: UnitTest
    dependsOn: PublishArtifacts
    displayName: 🧪 Unit test
    condition: succeeded()
    jobs:

      - template: jobs/run-unit-tests.yml
        parameters:
          vmImage: ubuntu-18.04
          sdkVersion: $(sdkVersion)
          buildConfiguration: $(buildConfiguration)
          projects: $(unitTestsProject)
          strategies:
            - Windows: windows-2019
            - Ubuntu: ubuntu-18.04
            - macOS: macOS-10.14

  - stage: IntegrationTests
    dependsOn: PublishArtifacts
    displayName: 🧪 Integreation tests
    # run integration tests only for pull requests that is coming from the same repo
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], False))
    jobs:
      - template: jobs/run-integration-tests.yml
        parameters:
          vmImage: $(vmImage)
          sdkVersion: $(sdkVersion)
          buildConfiguration: $(buildConfiguration)
          projects: $(integrationTestsProject)
