trigger: none
pr: none

variables:
  - template: variables.yml

stages:
  - stage: UnitTest
    displayName: 🧪 Unit test
    jobs:
      - template: jobs/run-unit-tests.yml
        parameters:
          sdkVersion: $(sdkVersion)
          buildConfiguration: $(buildConfiguration)
          projects: $(unitTestsProject)
          strategies:
            - Ubuntu: ubuntu-18.04
            - macOS: macos-10.14
            - Windows: windows-2019

  - stage: FullIntegrationTests
    displayName: 🧪 Full set of integration tests
    dependsOn: UnitTest
    condition: eq(variables['Build.SourceBranch'], 'develop')
    jobs:
      - template: jobs/run-integration-tests.yml
        parameters:
          vmImage: $(vmImage)
          sdkVersion: $(sdkVersion)
          buildConfiguration: $(buildConfiguration)
          projects: $(integrationTestsProject)

  - stage: NonInteractiveIntegrationTests
    displayName: 🧪 Non-interactive integration tests
    dependsOn: UnitTest
    condition: ne(variables['Build.SourceBranch'], 'develop')
    jobs:
      - template: jobs/run-integration-tests.yml
        parameters:
          vmImage: $(vmImage)
          sdkVersion: $(sdkVersion)
          buildConfiguration: $(buildConfiguration)
          projects: $(integrationTestsProject)
          arguments: --filter "Category!=Interactive"
